version: 'V1'

services:

  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "/home/vivek/de_zoomcamp_2025/ny_taxi_prostgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432" 

      

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "/home/vivek/de_zoomcamp_2025/pg_admin:/var/lib/pgadmin:rw"
    ports:
      - "8080:80"

    


  





